### ISSUE TITLE
Take byte slice instead of string

### ISSUE THREAD

**Issue by jesusrmoreno** [xyproto/simplebolt#1]
Is there a reason that you require a string instead of a byte slice? If we know that bolt saves a byte slice why require that it be a string? Doesn't that just limit the types of data that can be used?

If you take a byte slice instead of a string that opens it up for storing any arbitrary data such as gob encoded data, or json, etc..

**Comment by xyproto** [comment]
simplebolt (for BoltDB), simpleredis (for Redis) and simplemaria (for MariaDB/MySQL) all provide the same functions and satisfy the same [interface](https://github.com/xyproto/pinterface/blob/master/pinterface.go#L99). The communication with Redis and MariaDB is only via strings. Since the simple* database backends are meant to be interchangeable, also supporting bytes would require adding functions for handling bytes (with conversion from byte to string) for the database backends that require strings.

For now, only dealing with strings for simplebolt is a feature/limitation by design.

One solution is to add functions to only simplebolt and not the other, but then easy interchangeability of database engines would be lost.

Another solution could be to fork `simplebolt` and create something like `bytebolt`.

If performance is critical, using the Bolt database package directly might be most desirable.

I'm open for good ideas.

**Comment by jesusrmoreno** [comment]
Ah that makes sense then thanks for the prompt reply!
